name: Unit Tests
on:
  pull_request:
    branches:
      - master
jobs:
  Execute-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: ./simple-calc-test-runner --run unittests --reports-dir unit-test-reports
